# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno and run tests across stable and nightly builds on Windows, Ubuntu and macOS.
# For more information see: https://github.com/denolib/setup-deno

name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }} # runs a test on Ubuntu, Windows and macOS

    strategy:
      matrix:
        node-version: [16.x]
        os: [macOS-latest, ubuntu-latest]

    steps:
      - name: Setup Repo
        uses: actions/checkout@v2

      - name: Uses node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }} # tests across multiple Deno versions

      - name: Install all workspaces
        run: yarn install

      - name: Seutp contracts workspace
        run: yarn workspace @ampleforthorg/spot-contracts run compile

      - name: Lint
        run: yarn workspaces foreach run lint

      - name: Test
        run: yarn workspaces foreach run test
